base: &base
  adapter: postgresql
  encoding: utf8

development:
  database: styleguide_o_matic_development
  <<: *base
    
test:
  database: styleguide_o_matic_test<%= ENV['TEST_ENV_NUMBER'] %>
  <<: *base

production:
  <<: *base
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
