base: &base
  adapter: postgresql
  encoding: utf8

development:
  database: styleguide_o_matic_development
  <<: *base
    
test:
  database: styleguide_o_matic_test<%= ENV['TEST_ENV_NUMBER'] %>
  <<: *base
